platform :ios, '7.0'

pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'NHBalancedFlowLayout'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'HMSegmentedControl'
pod 'YTKNetwork'